server:
  port: 8083

spring:
  application:
    name: rest-ms-order-service

  r2dbc:
    url: ${ORDER_DB_URL:r2dbc:postgresql://localhost:5432/ms_order_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.restaurant.order.infrastructure.messaging.event.StockResultEvent
        spring.json.trusted.packages: com.restaurant.order.infrastructure.messaging.event

management:
  endpoints:
    web:
      exposure:
        include: health,info